language: node_js
node_js:
  - "node"

script: npm run test:chrome_puppeteer

sudo: false

dist: xenial
addons:
  chrome: stable
  firefox: latest

notifications:  
  email:
    recipients:
    - stepanchaparyan@gmail.com
    on_success: never
    on_failure: always

